
[functions.initialize-payment]
enabled = true
verify_jwt = false
import_map = "./functions/initialize-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-payment/*.html" ]

[functions.find-sponsor]
enabled = true
verify_jwt = false
import_map = "./functions/find-sponsor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/find-sponsor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/find-sponsor/*.html" ]

[functions.dashboard-stats]
enabled = true
verify_jwt = false
import_map = "./functions/dashboard-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dashboard-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dashboard-stats/*.html" ]

[functions.withdraw-request]
enabled = true
verify_jwt = false
import_map = "./functions/withdraw-request/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/withdraw-request/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/withdraw-request/*.html" ]

[functions.admin-dashboard-charts]
enabled = true
verify_jwt = false
import_map = "./functions/admin-dashboard-charts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-dashboard-charts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-dashboard-charts/*.html" ]

[functions.admin-top-affiliates]
enabled = true
verify_jwt = false
import_map = "./functions/admin-top-affiliates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-top-affiliates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-top-affiliates/*.html" ]

[functions.admin-top-products]
enabled = true
verify_jwt = false
import_map = "./functions/admin-top-products/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-top-products/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-top-products/*.html" ]

[functions.admin-affiliates]
enabled = true
verify_jwt = false
import_map = "./functions/admin-affiliates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-affiliates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-affiliates/*.html" ]

[functions.admin-affiliate-details]
enabled = true
verify_jwt = false
import_map = "./functions/admin-affiliate-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-affiliate-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-affiliate-details/*.html" ]

[functions.test-affiliate-stats]
enabled = true
verify_jwt = false
import_map = "./functions/test-affiliate-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-affiliate-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-affiliate-stats/*.html" ]
